dbt_project:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: Password
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev