# dbt_project:
#   outputs:
#     dev:
#       dbname: recruitment_task
#       host: recruitment.free.technology
#       pass: 9Mn9E3AbDPExgyR3stzJD6U7
#       port: 5432
#       schema: dev
#       threads: 1
#       type: postgres
#       user: samuel
#   target: dev

dbt_project:
  outputs:
    dev:
      dbname: postgres
      host: database
      pass: Password
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev