{
 "title": "Issue Distribution",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Issue Labels Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    label_name AS category,\n    COUNT(issue_id) AS issue_count\nFROM dim_issue_labels_clean  \nGROUP BY\n    label_name\nORDER BY\n    issue_count DESC"
    }
   ]
  },
  {
   "title": "Issue State Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    issue_state,\n    COUNT(issue_id) AS issue_count\nFROM\n   fact_issues \nGROUP BY\n    issue_state"
    }
   ]
  },
  {
   "title": "Assignees with Most issues",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    assignee_login AS assignee,\n    COUNT(issue_id) AS issue_count\nFROM\n    dim_issue_assignee_clean\nGROUP BY\n    assignee_login\nORDER BY\n    issue_count DESC;"
    }
   ]
  }
 ]
}