apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: database:5432
    user: admin
    secureJsonData:
      password: 'Password'
    jsonData:
      database: postgres
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      timescaledb: false
