{
 "title": "Project Cost Distribution",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cost By Currency",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    currency,\n    SUM(amount) AS currency_cost\nFROM\n    \"dim_project_cost _clean\"\nGROUP BY\n    currency;"
    }
   ]
  },
  {
   "title": "Costs Per Departments",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    department,\n    currency,\n    CONCAT(department, ' -> ', currency, '(', SUM(amount), ')') AS department_summary, \n    SUM(amount) AS department_cost \nFROM\n    \"dim_project_cost _clean\"\nGROUP BY\n    department, currency\nORDER BY\n    department, department_cost DESC;"
    }
   ]
  },
  {
   "title": "Total Monthly Project costs in USD",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(date, 'Month YYYY') AS month_name,\n    SUM(\n        CASE \n            WHEN currency = 'AOA' THEN amount * 1  \n            WHEN currency = 'EUR' THEN amount * 1.057  \n            WHEN currency = 'USD' THEN amount  \n            ELSE amount  \n        END\n    ) AS total_cost_in_usd                   \nFROM\n    \"dim_project_cost _clean\"\nGROUP BY\n    month_name\nORDER BY\n    MIN(date);"
    }
   ]
  },
  {
   "title": "Cost Over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    SUM(\n        CASE \n            WHEN currency = 'AOA' THEN amount * 1  \n            WHEN currency = 'EUR' THEN amount * 1.057  \n            WHEN currency = 'USD' THEN amount  \n            ELSE amount \n        END\n    ) AS daily_cost_in_usd\nFROM\n    \"dim_project_cost _clean\" \nGROUP BY\n    date\nORDER BY\n    date;"
    }
   ]
  }
 ]
}